<?php

namespace Database\Seeders\Concerns;

use App\Models\AssetModel;
use App\Models\AttributeDefinition;
use App\Models\Category;
use App\Models\Manufacturer;

trait ProvidesDeviceCatalogData
{
    /**
     * Attribute definitions used across laptops/phones.
     *
     * @return array<string,array<string,mixed>>
     */
    protected function attributeBlueprints(): array
    {
        return [
            'release_year' => [
                'label' => 'Introductiejaar',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 2005, 'max' => (int) date('Y'), 'step' => 1],
                'required' => true,
            ],
            'cpu_model' => [
                'label' => 'Processor',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
                'required' => true,
            ],
            'cpu_core_count' => [
                'label' => 'Processorkernen',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'categories' => ['Laptops'],
                'constraints' => ['min' => 2, 'max' => 32, 'step' => 1],
            ],
            'gpu_model' => [
                'label' => 'Grafische kaart',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
            ],
            'ram_size_gb' => [
                'label' => 'Werkgeheugen (GB)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'GB',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 1, 'max' => 64, 'step' => 1],
                'required' => true,
                'allow_asset_override' => true,
            ],
            'ram_type' => [
                'label' => 'Geheugentype',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'ddr4', 'label' => 'DDR4'],
                    ['value' => 'ddr5', 'label' => 'DDR5'],
                    ['value' => 'lpddr4x', 'label' => 'LPDDR4X'],
                    ['value' => 'lpddr5', 'label' => 'LPDDR5'],
                    ['value' => 'lpddr5x', 'label' => 'LPDDR5X'],
                    ['value' => 'lpddr3', 'label' => 'LPDDR3'],
                ],
            ],
            'storage_capacity_gb' => [
                'label' => 'Opslagcapaciteit (GB)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'GB',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 16, 'max' => 4096, 'step' => 1],
                'required' => true,
                'allow_asset_override' => true,
            ],
            'storage_type' => [
                'label' => 'Opslagtype',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'nvme', 'label' => 'NVMe-SSD'],
                    ['value' => 'ssd', 'label' => 'SATA-SSD'],
                    ['value' => 'hdd', 'label' => 'Harde schijf'],
                    ['value' => 'ufs', 'label' => 'UFS-opslag'],
                ],
            ],
            'display_size_inches' => [
                'label' => 'Schermgrootte (inch)',
                'datatype' => AttributeDefinition::DATATYPE_DECIMAL,
                'unit' => 'in',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 3.0, 'max' => 18.0, 'step' => 0.1],
            ],
            'display_resolution' => [
                'label' => 'Schermresolutie',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'display_panel_type' => [
                'label' => 'Schermtechnologie',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'ips', 'label' => 'IPS'],
                    ['value' => 'oled', 'label' => 'OLED'],
                    ['value' => 'amoled', 'label' => 'AMOLED'],
                    ['value' => 'tn', 'label' => 'TN'],
                ],
            ],
            'display_refresh_rate_hz' => [
                'label' => 'Verversingssnelheid (Hz)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'Hz',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 30, 'max' => 240, 'step' => 1],
            ],
            'weight_kg' => [
                'label' => 'Gewicht (kg)',
                'datatype' => AttributeDefinition::DATATYPE_DECIMAL,
                'unit' => 'kg',
                'categories' => ['Laptops'],
                'constraints' => ['min' => 0.5, 'max' => 5.0, 'step' => 0.01],
            ],
            'battery_capacity' => [
                'label' => 'Batterijcapaciteit',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
                'allow_custom_values' => true,
                'required' => true,
            ],
            'battery_health_percent' => [
                'label' => 'Batterijgezondheid (%)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => '%',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 0, 'max' => 100, 'step' => 1],
                'allow_asset_override' => true,
            ],
            'keyboard_layout' => [
                'label' => 'Toetsenbordindeling',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops'],
                'options' => [
                    ['value' => 'us', 'label' => 'US (ANSI)'],
                    ['value' => 'uk', 'label' => 'UK'],
                    ['value' => 'iso', 'label' => 'EU (ISO)'],
                ],
            ],
            'webcam_present' => [
                'label' => 'Webcam aanwezig',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
            ],
            'supports_5g' => [
                'label' => '5G-ondersteuning',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
            ],
            'rear_camera_megapixels' => [
                'label' => 'Hoofdcamera (MP)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'MP',
                'categories' => ['Mobile Phones'],
                'constraints' => ['min' => 2, 'max' => 200, 'step' => 1],
            ],
            'front_camera_megapixels' => [
                'label' => 'Selfiecamera (MP)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'MP',
                'categories' => ['Mobile Phones'],
                'constraints' => ['min' => 2, 'max' => 64, 'step' => 1],
            ],
            'os_family' => [
                'label' => 'Besturingssysteem',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'windows', 'label' => 'Windows'],
                    ['value' => 'macos', 'label' => 'macOS'],
                    ['value' => 'chromeos', 'label' => 'ChromeOS'],
                    ['value' => 'linux', 'label' => 'Linux'],
                    ['value' => 'android', 'label' => 'Android'],
                    ['value' => 'ios', 'label' => 'iOS'],
                ],
            ],
            'os_version' => [
                'label' => 'OS-versie',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'warranty_months' => [
                'label' => 'Garantie (maanden)',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'maanden',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 0, 'max' => 36, 'step' => 1],
            ],
            'condition_grade' => [
                'label' => 'Cosmetische staat',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'grade_a', 'label' => 'A-kwaliteit'],
                    ['value' => 'grade_b', 'label' => 'B-kwaliteit'],
                    ['value' => 'grade_c', 'label' => 'C-kwaliteit'],
                ],
                'allow_asset_override' => true,
            ],
            'color' => [
                'label' => 'Kleur',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'usb_ports_summary' => [
                'label' => 'USB-aansluitingen',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
                'allow_custom_values' => true,
            ],
            'video_outputs_summary' => [
                'label' => 'Video-uitgangen',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
                'allow_custom_values' => true,
            ],
            'audio_connectors_summary' => [
                'label' => 'Audio-aansluitingen',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
                'allow_custom_values' => true,
            ],
            'included_accessories' => [
                'label' => 'Meegeleverde accessoires',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_custom_values' => true,
                'allow_asset_override' => true,
            ],
            'charger_included' => [
                'label' => 'Oplader meegeleverd',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'charging_port_type' => [
                'label' => 'Laadpoort',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Mobile Phones'],
                'options' => [
                    ['value' => 'usb-c', 'label' => 'USB-C'],
                    ['value' => 'lightning', 'label' => 'Lightning'],
                    ['value' => 'mag-safe', 'label' => 'MagSafe'],
                ],
            ],
            'ip_rating' => [
                'label' => 'IP-classificatie',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Mobile Phones'],
                'options' => [
                    ['value' => 'ip68', 'label' => 'IP68'],
                    ['value' => 'ip67', 'label' => 'IP67'],
                    ['value' => 'ip54', 'label' => 'IP54'],
                ],
            ],
            // Test attributes
            'wifi_test' => [
                'label' => 'Wifi-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'bluetooth_test' => [
                'label' => 'Bluetooth-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'speaker_test' => [
                'label' => 'Luidsprekertest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'microphone_test' => [
                'label' => 'Microfoontest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'display_test' => [
                'label' => 'Schermtest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'battery_test' => [
                'label' => 'Batterijtest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'webcam_test' => [
                'label' => 'Webcamtest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'front_camera_test' => [
                'label' => 'Selfiecamera-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'rear_camera_test' => [
                'label' => 'Hoofdcamera-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'face_unlock_test' => [
                'label' => 'Gezichtsherkenningstest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'ethernet_test' => [
                'label' => 'Ethernet-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'usb_ports_test' => [
                'label' => 'USB-poortentest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'sd_card_reader_test' => [
                'label' => 'SD-kaartlezertest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'hdmi_test' => [
                'label' => 'HDMI-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'vga_test' => [
                'label' => 'VGA-test',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'keyboard_test' => [
                'label' => 'Toetsentest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'touchpad_test' => [
                'label' => 'Touchpadtest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'cpu_test' => [
                'label' => 'Processortest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'ram_test' => [
                'label' => 'Geheugentest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'storage_test' => [
                'label' => 'Opslagtest',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
        ];
    }

    /**
     * Primary models that power the demo assets inventory.
     */
    protected function demoModelKeys(): array
    {
        return [
            'HP ProBook 450 G8',
            'HP ProBook 430 G7',
            'Samsung Galaxy A5',
            'Pixel 8 Pro',
        ];
    }

    /**
     * Additional catalog entries we seed for more realistic refurb scenarios.
     */
    protected function expansionModelKeys(): array
    {
        return [
            'HP ProBook 450 G7',
            'HP ProBook 450 G6',
            'HP ProBook 430 G6',
            'HP ProBook 430 G3',
            'Microsoft Surface Pro 4',
            'Microsoft Surface Pro 5',
        ];
    }

    /**
     * Reference device presets for demo/catalog purposes.
     *
     * @return array<string,array<string,mixed>>
     */
    protected function modelBlueprints(): array
    {
        return [
            'HP ProBook 450 G8' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 450 G8',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '36',
                ]),
                'code' => 'HP-450G8-I5-16-512',
                'label' => 'HP ProBook 450 G8 - i5 - 16GB - 512GB',
                'attributes' => [
                    'release_year' => 2021,
                    'cpu_model' => 'Intel Core i5-1135G7',
                    'cpu_core_count' => 4,
                    'gpu_model' => 'Intel Iris Xe Graphics',
                    'ram_size_gb' => 16,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 512,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 15.6,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.74,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 94,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.2, 1x USB-C, HDMI 1.4b, RJ-45',
                    'video_outputs_summary' => 'HDMI 1.4b, USB-C DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '65W USB-C-voeding, USB-C-oplaadkabel',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Pike Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'HP ProBook 450 G7' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 450 G7',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '36',
                ]),
                'code' => 'HP-450G7-I5-16-512',
                'label' => 'HP ProBook 450 G7 - i5 - 16GB - 512GB',
                'attributes' => [
                    'release_year' => 2020,
                    'cpu_model' => 'Intel Core i5-10210U',
                    'cpu_core_count' => 4,
                    'gpu_model' => 'Intel UHD Graphics',
                    'ram_size_gb' => 16,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 512,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 15.6,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.74,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 92,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.1, 1x USB-C, HDMI 1.4b, RJ-45',
                    'video_outputs_summary' => 'HDMI 1.4b, USB-C DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '65W USB-C-voeding, USB-C-kabel',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_b',
                    'color' => 'Pike Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'HP ProBook 450 G6' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 450 G6',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '36',
                ]),
                'code' => 'HP-450G6-I5-8-256',
                'label' => 'HP ProBook 450 G6 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2019,
                    'cpu_model' => 'Intel Core i5-8265U',
                    'cpu_core_count' => 4,
                    'gpu_model' => 'Intel UHD Graphics 620',
                    'ram_size_gb' => 8,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 15.6,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.96,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 88,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.1, 1x USB-C, HDMI 1.4b, RJ-45',
                    'video_outputs_summary' => 'HDMI 1.4b, USB-C DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '65W USB-C-voeding',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_c',
                    'color' => 'Ash Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'HP ProBook 430 G7' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 430 G7',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '36',
                ]),
                'code' => 'HP-430G7-I5-8-256',
                'label' => 'HP ProBook 430 G7 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2020,
                    'cpu_model' => 'Intel Core i5-10210U',
                    'cpu_core_count' => 4,
                    'gpu_model' => 'Intel UHD Graphics',
                    'ram_size_gb' => 8,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 13.3,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.28,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 91,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.1, 1x USB-C, HDMI 1.4b',
                    'video_outputs_summary' => 'HDMI 1.4b, USB-C DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '45W USB-C-voeding',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_b',
                    'color' => 'Natural Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'HP ProBook 430 G6' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 430 G6',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '36',
                ]),
                'code' => 'HP-430G6-I5-8-256',
                'label' => 'HP ProBook 430 G6 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2019,
                    'cpu_model' => 'Intel Core i5-8265U',
                    'cpu_core_count' => 4,
                    'gpu_model' => 'Intel UHD Graphics 620',
                    'ram_size_gb' => 8,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 13.3,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.28,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 90,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.1, 1x USB-C, HDMI 1.4b, RJ-45',
                    'video_outputs_summary' => 'HDMI 1.4b, USB-C DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '45W USB-C-voeding',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_b',
                    'color' => 'Natural Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'HP ProBook 430 G3' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'HP ProBook 430 G3',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'HP')->value('id')
                        ?? Manufacturer::factory()->hp()->create()->id,
                    'eol' => '24',
                ]),
                'code' => 'HP-430G3-I5-8-256',
                'label' => 'HP ProBook 430 G3 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2016,
                    'cpu_model' => 'Intel Core i5-6200U',
                    'cpu_core_count' => 2,
                    'gpu_model' => 'Intel HD Graphics 520',
                    'ram_size_gb' => 8,
                    'ram_type' => 'ddr4',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'ssd',
                    'display_size_inches' => 13.3,
                    'display_resolution' => '1366 x 768',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.5,
                    'battery_capacity' => '44 Wh',
                    'battery_health_percent' => 82,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '2x USB-A 3.0, 1x USB-A 2.0, VGA, HDMI',
                    'video_outputs_summary' => 'HDMI 1.4, VGA',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '45W barrel-voeding',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 10 Pro',
                    'warranty_months' => 6,
                    'condition_grade' => 'grade_c',
                    'color' => 'Ash Silver',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => true,
                ],
            ],
            'Samsung Galaxy A5' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'Samsung Galaxy A5',
                    'category_id' => Category::where('name', 'Mobile Phones')->value('id')
                        ?? Category::factory()->assetMobileCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'Samsung')->value('id')
                        ?? Manufacturer::factory()->samsung()->create()->id,
                    'eol' => '18',
                ]),
                'code' => 'SM-A520-32-BLACK',
                'label' => 'Samsung Galaxy A5 (2017) - 32GB - Zwart',
                'attributes' => [
                    'release_year' => 2017,
                    'ram_size_gb' => 3,
                    'ram_type' => 'lpddr4x',
                    'storage_capacity_gb' => 32,
                    'storage_type' => 'ufs',
                    'display_size_inches' => 5.2,
                    'display_resolution' => '1920 x 1080',
                    'display_panel_type' => 'amoled',
                    'display_refresh_rate_hz' => 60,
                    'battery_capacity' => '3000 mAh',
                    'battery_health_percent' => 82,
                    'rear_camera_megapixels' => 16,
                    'front_camera_megapixels' => 16,
                    'supports_5g' => false,
                    'os_family' => 'android',
                    'os_version' => 'Android 8.0',
                    'warranty_months' => 6,
                    'condition_grade' => 'grade_b',
                    'color' => 'Black Sky',
                    'charger_included' => true,
                    'included_accessories' => '15W oplader, USB-C-kabel',
                    'charging_port_type' => 'usb-c',
                    'ip_rating' => 'ip68',
                    'display_test' => true,
                    'front_camera_test' => true,
                    'rear_camera_test' => true,
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'battery_test' => true,
                ],
            ],
            'Microsoft Surface Pro 4' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'Microsoft Surface Pro 4',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'Microsoft')->value('id')
                        ?? Manufacturer::factory()->microsoft()->create()->id,
                    'eol' => '30',
                ]),
                'code' => 'MS-SURFPRO4-I5-8-256',
                'label' => 'Microsoft Surface Pro 4 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2015,
                    'cpu_model' => 'Intel Core i5-6300U',
                    'cpu_core_count' => 2,
                    'gpu_model' => 'Intel HD Graphics 520',
                    'ram_size_gb' => 8,
                    'ram_type' => 'lpddr3',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 12.3,
                    'display_resolution' => '2736 x 1824',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 0.79,
                    'battery_capacity' => '38 Wh',
                    'battery_health_percent' => 80,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '1x USB-A 3.0, Mini DisplayPort, Surface Connect',
                    'video_outputs_summary' => 'Mini DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '65W Surface Connect-voeding, Surface Pen',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 10 Pro',
                    'warranty_months' => 6,
                    'condition_grade' => 'grade_b',
                    'color' => 'Platinum',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => false,
                ],
            ],
            'Microsoft Surface Pro 5' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'Microsoft Surface Pro 5',
                    'category_id' => Category::where('name', 'Laptops')->value('id')
                        ?? Category::factory()->assetLaptopCategory()->create()->id,
                    'manufacturer_id' => Manufacturer::where('name', 'Microsoft')->value('id')
                        ?? Manufacturer::factory()->microsoft()->create()->id,
                    'eol' => '30',
                ]),
                'code' => 'MS-SURFPRO5-I5-8-256',
                'label' => 'Microsoft Surface Pro 5 - i5 - 8GB - 256GB',
                'attributes' => [
                    'release_year' => 2017,
                    'cpu_model' => 'Intel Core i5-7300U',
                    'cpu_core_count' => 2,
                    'gpu_model' => 'Intel HD Graphics 620',
                    'ram_size_gb' => 8,
                    'ram_type' => 'lpddr3',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'nvme',
                    'display_size_inches' => 12.3,
                    'display_resolution' => '2736 x 1824',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 0.78,
                    'battery_capacity' => '45 Wh',
                    'battery_health_percent' => 87,
                    'keyboard_layout' => 'us',
                    'webcam_present' => true,
                    'usb_ports_summary' => '1x USB-A 3.0, Mini DisplayPort, Surface Connect',
                    'video_outputs_summary' => 'Mini DisplayPort',
                    'audio_connectors_summary' => '3,5 mm audio',
                    'charger_included' => true,
                    'included_accessories' => '65W Surface Connect-voeding, Type Cover',
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Platinum',
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'webcam_test' => true,
                    'keyboard_test' => true,
                    'touchpad_test' => true,
                    'display_test' => true,
                    'cpu_test' => true,
                    'ram_test' => true,
                    'storage_test' => true,
                    'battery_test' => true,
                    'usb_ports_test' => true,
                    'sd_card_reader_test' => true,
                    'ethernet_test' => false,
                ],
            ],
            'iPhone 12' => [
                'factory' => fn () => AssetModel::factory()->iphone12Model()->create(),
                'code' => 'IP12-128-BLUE',
                'label' => 'iPhone 12 – 128GB – Simlockvrij',
                'attributes' => [
                    'release_year' => 2020,
                    'ram_size_gb' => 4,
                    'ram_type' => 'lpddr4x',
                    'storage_capacity_gb' => 128,
                    'storage_type' => 'ufs',
                    'display_size_inches' => 6.1,
                    'display_resolution' => '2532 x 1170',
                    'display_panel_type' => 'oled',
                    'display_refresh_rate_hz' => 60,
                    'battery_capacity' => '2815 mAh',
                    'battery_health_percent' => 89,
                    'rear_camera_megapixels' => 12,
                    'front_camera_megapixels' => 12,
                    'supports_5g' => true,
                    'os_family' => 'ios',
                    'os_version' => 'iOS 18',
                    'warranty_months' => 6,
                    'condition_grade' => 'grade_a',
                    'color' => 'Pacific Blue',
                    'charger_included' => false,
                    'included_accessories' => 'USB-C-naar-Lightning-kabel',
                    'charging_port_type' => 'lightning',
                    'ip_rating' => 'ip68',
                    'display_test' => true,
                    'front_camera_test' => true,
                    'rear_camera_test' => true,
                    'face_unlock_test' => true,
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'battery_test' => true,
                ],
            ],
            'Pixel 8 Pro' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'Pixel 8 Pro',
                    'category_id' => Category::where('name', 'Mobile Phones')->value('id')
                        ?? Category::factory()->assetMobileCategory()->create()->id,
                ]),
                'code' => 'PIXEL8PRO-256-OBSIDIAN',
                'label' => 'Pixel 8 Pro – 256GB – Obsidian',
                'attributes' => [
                    'release_year' => 2023,
                    'ram_size_gb' => 12,
                    'ram_type' => 'lpddr5x',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'ufs',
                    'display_size_inches' => 6.7,
                    'display_resolution' => '2992 x 1344',
                    'display_panel_type' => 'oled',
                    'display_refresh_rate_hz' => 120,
                    'battery_capacity' => '5050 mAh',
                    'battery_health_percent' => 97,
                    'rear_camera_megapixels' => 50,
                    'front_camera_megapixels' => 10,
                    'supports_5g' => true,
                    'os_family' => 'android',
                    'os_version' => 'Android 14',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Obsidian',
                    'charger_included' => false,
                    'included_accessories' => 'USB-C-kabel (1 m)',
                    'charging_port_type' => 'usb-c',
                    'ip_rating' => 'ip68',
                    'display_test' => true,
                    'front_camera_test' => true,
                    'rear_camera_test' => true,
                    'wifi_test' => true,
                    'bluetooth_test' => true,
                    'speaker_test' => true,
                    'microphone_test' => true,
                    'battery_test' => true,
                ],
            ],
        ];
    }
}
