<?php

namespace Database\Seeders\Concerns;

use App\Models\AssetModel;
use App\Models\AttributeDefinition;
use App\Models\Category;

trait ProvidesDeviceCatalogData
{
    /**
     * Attribute definitions used across laptops/phones.
     *
     * @return array<string,array<string,mixed>>
     */
    protected function attributeBlueprints(): array
    {
        return [
            'device_class' => [
                'label' => 'Device Class',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'required' => true,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'laptop', 'label' => 'Laptop'],
                    ['value' => 'phone', 'label' => 'Phone'],
                    ['value' => 'tablet', 'label' => 'Tablet'],
                ],
            ],
            'brand' => [
                'label' => 'Brand',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => false,
            ],
            'product_line' => [
                'label' => 'Product Line',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'release_year' => [
                'label' => 'Release Year',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 2005, 'max' => (int) date('Y'), 'step' => 1],
            ],
            'cpu_model' => [
                'label' => 'CPU Model',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
            ],
            'cpu_generation' => [
                'label' => 'CPU Generation',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
            ],
            'cpu_core_count' => [
                'label' => 'CPU Cores',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'categories' => ['Laptops'],
                'constraints' => ['min' => 2, 'max' => 32, 'step' => 1],
            ],
            'soc_model' => [
                'label' => 'SoC Model',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Mobile Phones'],
            ],
            'ram_size_gb' => [
                'label' => 'Memory',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'GB',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 1, 'max' => 64, 'step' => 1],
            ],
            'ram_type' => [
                'label' => 'Memory Type',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'ddr4', 'label' => 'DDR4'],
                    ['value' => 'ddr5', 'label' => 'DDR5'],
                    ['value' => 'lpddr4x', 'label' => 'LPDDR4X'],
                    ['value' => 'lpddr5', 'label' => 'LPDDR5'],
                    ['value' => 'lpddr5x', 'label' => 'LPDDR5X'],
                ],
            ],
            'storage_capacity_gb' => [
                'label' => 'Storage Capacity',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'GB',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 16, 'max' => 4096, 'step' => 1],
            ],
            'storage_type' => [
                'label' => 'Storage Type',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'nvme', 'label' => 'NVMe SSD'],
                    ['value' => 'ssd', 'label' => 'SATA SSD'],
                    ['value' => 'hdd', 'label' => 'Hard Disk Drive'],
                    ['value' => 'ufs', 'label' => 'UFS Storage'],
                ],
            ],
            'gpu_model' => [
                'label' => 'Graphics',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
            ],
            'display_size_inches' => [
                'label' => 'Display Size',
                'datatype' => AttributeDefinition::DATATYPE_DECIMAL,
                'unit' => 'in',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 3.0, 'max' => 18.0, 'step' => 0.1],
            ],
            'display_resolution' => [
                'label' => 'Display Resolution',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'display_panel_type' => [
                'label' => 'Panel Type',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'ips', 'label' => 'IPS'],
                    ['value' => 'oled', 'label' => 'OLED'],
                    ['value' => 'amoled', 'label' => 'AMOLED'],
                    ['value' => 'tn', 'label' => 'TN'],
                ],
            ],
            'display_refresh_rate_hz' => [
                'label' => 'Refresh Rate',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'Hz',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 30, 'max' => 240, 'step' => 1],
            ],
            'weight_kg' => [
                'label' => 'Weight',
                'datatype' => AttributeDefinition::DATATYPE_DECIMAL,
                'unit' => 'kg',
                'categories' => ['Laptops'],
                'constraints' => ['min' => 0.5, 'max' => 5.0, 'step' => 0.01],
            ],
            'battery_capacity_wh' => [
                'label' => 'Battery Capacity',
                'datatype' => AttributeDefinition::DATATYPE_DECIMAL,
                'unit' => 'Wh',
                'categories' => ['Laptops'],
                'constraints' => ['min' => 10, 'max' => 120],
            ],
            'battery_capacity_mah' => [
                'label' => 'Battery Capacity',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'mAh',
                'categories' => ['Mobile Phones'],
                'constraints' => ['min' => 1500, 'max' => 7000, 'step' => 1],
            ],
            'battery_health_percent' => [
                'label' => 'Battery Health',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => '%',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 0, 'max' => 100, 'step' => 1],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'keyboard_layout' => [
                'label' => 'Keyboard Layout',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops'],
                'options' => [
                    ['value' => 'us', 'label' => 'US ANSI'],
                    ['value' => 'uk', 'label' => 'UK'],
                    ['value' => 'iso', 'label' => 'EU ISO'],
                ],
            ],
            'keyboard_functional' => [
                'label' => 'Keyboard Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'wifi_functional' => [
                'label' => 'Wi-Fi Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'bluetooth_functional' => [
                'label' => 'Bluetooth Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'speaker_functional' => [
                'label' => 'Speakers Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'microphone_functional' => [
                'label' => 'Microphone Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'webcam_functional' => [
                'label' => 'Webcam Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'camera_functional' => [
                'label' => 'Camera Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'face_unlock_functional' => [
                'label' => 'Face Unlock Functional',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
                'needs_test' => true,
                'allow_asset_override' => true,
            ],
            'supports_5g' => [
                'label' => '5G Support',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Mobile Phones'],
            ],
            'carrier_lock_status' => [
                'label' => 'Carrier Lock Status',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Mobile Phones'],
                'options' => [
                    ['value' => 'unlocked', 'label' => 'Factory Unlocked'],
                    ['value' => 'factory_locked', 'label' => 'Factory Locked'],
                    ['value' => 'carrier_locked', 'label' => 'Carrier Locked'],
                ],
            ],
            'rear_camera_megapixels' => [
                'label' => 'Rear Camera',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'MP',
                'categories' => ['Mobile Phones'],
                'constraints' => ['min' => 2, 'max' => 200, 'step' => 1],
            ],
            'front_camera_megapixels' => [
                'label' => 'Front Camera',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'MP',
                'categories' => ['Mobile Phones'],
                'constraints' => ['min' => 2, 'max' => 64, 'step' => 1],
            ],
            'os_family' => [
                'label' => 'Operating System',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'windows', 'label' => 'Windows'],
                    ['value' => 'macos', 'label' => 'macOS'],
                    ['value' => 'chromeos', 'label' => 'ChromeOS'],
                    ['value' => 'linux', 'label' => 'Linux'],
                    ['value' => 'android', 'label' => 'Android'],
                    ['value' => 'ios', 'label' => 'iOS'],
                ],
            ],
            'os_version' => [
                'label' => 'OS Version',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_asset_override' => true,
            ],
            'warranty_months' => [
                'label' => 'Warranty',
                'datatype' => AttributeDefinition::DATATYPE_INT,
                'unit' => 'months',
                'categories' => ['Laptops', 'Mobile Phones'],
                'constraints' => ['min' => 0, 'max' => 36, 'step' => 1],
            ],
            'condition_grade' => [
                'label' => 'Cosmetic Grade',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'grade_a', 'label' => 'Grade A'],
                    ['value' => 'grade_b', 'label' => 'Grade B'],
                    ['value' => 'grade_c', 'label' => 'Grade C'],
                ],
            ],
            'color' => [
                'label' => 'Colour',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'port_configuration' => [
                'label' => 'Ports',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops'],
                'allow_asset_override' => true,
            ],
            'charger_included' => [
                'label' => 'Charger Included',
                'datatype' => AttributeDefinition::DATATYPE_BOOL,
                'categories' => ['Laptops', 'Mobile Phones'],
            ],
            'included_accessories' => [
                'label' => 'Included Accessories',
                'datatype' => AttributeDefinition::DATATYPE_TEXT,
                'categories' => ['Laptops', 'Mobile Phones'],
                'allow_custom_values' => true,
                'allow_asset_override' => true,
            ],
            'charging_port_type' => [
                'label' => 'Charging Port',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Laptops', 'Mobile Phones'],
                'options' => [
                    ['value' => 'usb-c', 'label' => 'USB-C'],
                    ['value' => 'lightning', 'label' => 'Lightning'],
                    ['value' => 'mag-safe', 'label' => 'MagSafe'],
                    ['value' => 'usb-a', 'label' => 'USB-A'],
                ],
            ],
            'ip_rating' => [
                'label' => 'IP Rating',
                'datatype' => AttributeDefinition::DATATYPE_ENUM,
                'categories' => ['Mobile Phones'],
                'options' => [
                    ['value' => 'ip68', 'label' => 'IP68'],
                    ['value' => 'ip67', 'label' => 'IP67'],
                    ['value' => 'ip54', 'label' => 'IP54'],
                ],
            ],
        ];
    }

    /**
     * Reference device presets for demo/catalog purposes.
     *
     * @return array<string,array<string,mixed>>
     */
    protected function modelBlueprints(): array
    {
        return [
            'Macbook Pro 13"' => [
                'factory' => fn () => AssetModel::factory()->mbp13Model()->create(),
                'code' => 'MBP13-2019-I5-16G-512',
                'label' => 'MacBook Pro 13" · i5 · 16GB · 512GB',
                'attributes' => [
                    'device_class' => 'laptop',
                    'brand' => 'Apple',
                    'product_line' => 'MacBook Pro',
                    'release_year' => 2019,
                    'cpu_model' => 'Intel Core i5-8279U',
                    'cpu_generation' => '8th Gen Coffee Lake',
                    'cpu_core_count' => 4,
                    'ram_size_gb' => 16,
                    'ram_type' => 'lpddr3',
                    'storage_capacity_gb' => 512,
                    'storage_type' => 'nvme',
                    'gpu_model' => 'Intel Iris Plus 655',
                    'display_size_inches' => 13.3,
                    'display_resolution' => '2560 x 1600',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.37,
                    'battery_capacity_wh' => 58.2,
                    'battery_health_percent' => 92,
                    'keyboard_layout' => 'us',
                    'keyboard_functional' => true,
                    'wifi_functional' => true,
                    'bluetooth_functional' => true,
                    'speaker_functional' => true,
                    'microphone_functional' => true,
                    'webcam_functional' => true,
                    'camera_functional' => true,
                    'face_unlock_functional' => false,
                    'supports_5g' => false,
                    'os_family' => 'macos',
                    'os_version' => 'macOS Sonoma 14.3',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Space Gray',
                    'port_configuration' => '2× Thunderbolt 3, 1× 3.5mm audio',
                    'charger_included' => true,
                    'included_accessories' => '67W USB-C power adapter, USB-C charge cable',
                    'charging_port_type' => 'usb-c',
                ],
            ],
            'XPS 13' => [
                'factory' => fn () => AssetModel::factory()->xps13Model()->create(),
                'code' => 'XPS13-9310-I7-16G-512',
                'label' => 'Dell XPS 13 · i7 · 16GB · 512GB',
                'attributes' => [
                    'device_class' => 'laptop',
                    'brand' => 'Dell',
                    'product_line' => 'XPS 13 9310',
                    'release_year' => 2021,
                    'cpu_model' => 'Intel Core i7-1165G7',
                    'cpu_generation' => '11th Gen Tiger Lake',
                    'cpu_core_count' => 4,
                    'ram_size_gb' => 16,
                    'ram_type' => 'lpddr4x',
                    'storage_capacity_gb' => 512,
                    'storage_type' => 'nvme',
                    'gpu_model' => 'Intel Iris Xe Graphics',
                    'display_size_inches' => 13.4,
                    'display_resolution' => '3840 x 2400',
                    'display_panel_type' => 'ips',
                    'display_refresh_rate_hz' => 60,
                    'weight_kg' => 1.2,
                    'battery_capacity_wh' => 52,
                    'battery_health_percent' => 95,
                    'keyboard_layout' => 'us',
                    'keyboard_functional' => true,
                    'wifi_functional' => true,
                    'bluetooth_functional' => true,
                    'speaker_functional' => true,
                    'microphone_functional' => true,
                    'webcam_functional' => true,
                    'camera_functional' => true,
                    'face_unlock_functional' => false,
                    'supports_5g' => false,
                    'os_family' => 'windows',
                    'os_version' => 'Windows 11 Pro',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Platinum Silver',
                    'port_configuration' => '2× Thunderbolt 4, 1× microSD, 1× 3.5mm audio',
                    'charger_included' => true,
                    'included_accessories' => '45W USB-C power adapter',
                    'charging_port_type' => 'usb-c',
                ],
            ],
            'iPhone 12' => [
                'factory' => fn () => AssetModel::factory()->iphone12Model()->create(),
                'code' => 'IP12-128-BLUE',
                'label' => 'iPhone 12 · 128GB · Unlocked',
                'attributes' => [
                    'device_class' => 'phone',
                    'brand' => 'Apple',
                    'product_line' => 'iPhone',
                    'release_year' => 2020,
                    'soc_model' => 'A14 Bionic',
                    'ram_size_gb' => 4,
                    'ram_type' => 'lpddr4x',
                    'storage_capacity_gb' => 128,
                    'storage_type' => 'ufs',
                    'display_size_inches' => 6.1,
                    'display_resolution' => '2532 x 1170',
                    'display_panel_type' => 'oled',
                    'display_refresh_rate_hz' => 60,
                    'battery_capacity_mah' => 2815,
                    'battery_health_percent' => 89,
                    'wifi_functional' => true,
                    'bluetooth_functional' => true,
                    'speaker_functional' => true,
                    'microphone_functional' => true,
                    'camera_functional' => true,
                    'face_unlock_functional' => true,
                    'supports_5g' => true,
                    'carrier_lock_status' => 'unlocked',
                    'rear_camera_megapixels' => 12,
                    'front_camera_megapixels' => 12,
                    'os_family' => 'ios',
                    'os_version' => 'iOS 18',
                    'warranty_months' => 6,
                    'condition_grade' => 'grade_a',
                    'color' => 'Pacific Blue',
                    'charger_included' => false,
                    'included_accessories' => 'USB-C to Lightning cable',
                    'charging_port_type' => 'lightning',
                    'ip_rating' => 'ip68',
                ],
            ],
            'Pixel 8 Pro' => [
                'factory' => fn () => AssetModel::factory()->create([
                    'name' => 'Pixel 8 Pro',
                    'category_id' => Category::where('name', 'Mobile Phones')->value('id')
                        ?? Category::factory()->assetMobileCategory()->create()->id,
                ]),
                'code' => 'PIXEL8PRO-256-OBSIDIAN',
                'label' => 'Pixel 8 Pro · 256GB · Obsidian',
                'attributes' => [
                    'device_class' => 'phone',
                    'brand' => 'Google',
                    'product_line' => 'Pixel',
                    'release_year' => 2023,
                    'soc_model' => 'Google Tensor G3',
                    'ram_size_gb' => 12,
                    'ram_type' => 'lpddr5x',
                    'storage_capacity_gb' => 256,
                    'storage_type' => 'ufs',
                    'display_size_inches' => 6.7,
                    'display_resolution' => '2992 x 1344',
                    'display_panel_type' => 'oled',
                    'display_refresh_rate_hz' => 120,
                    'battery_capacity_mah' => 5050,
                    'battery_health_percent' => 97,
                    'wifi_functional' => true,
                    'bluetooth_functional' => true,
                    'speaker_functional' => true,
                    'microphone_functional' => true,
                    'camera_functional' => true,
                    'face_unlock_functional' => true,
                    'supports_5g' => true,
                    'carrier_lock_status' => 'unlocked',
                    'rear_camera_megapixels' => 50,
                    'front_camera_megapixels' => 10,
                    'os_family' => 'android',
                    'os_version' => 'Android 14',
                    'warranty_months' => 12,
                    'condition_grade' => 'grade_a',
                    'color' => 'Obsidian',
                    'charger_included' => false,
                    'included_accessories' => '1m USB-C cable',
                    'charging_port_type' => 'usb-c',
                    'ip_rating' => 'ip68',
                ],
            ],
        ];
    }
}
