
@extends('layouts/edit-form', [
    'createText' => trans('admin/hardware/form.create'),
    'updateText' => trans('admin/hardware/form.update'),
    'topSubmit' => true,
    'helpText' => trans('help.assets'),
    'helpPosition' => 'right',
    'formAction' => ($item->id) ? route('hardware.update', $item) : route('hardware.store'),
    'index_route' => 'hardware.index',
    'options' => [
                'back' => trans('admin/hardware/form.redirect_to_type',['type' => trans('general.previous_page')]),
                'index' => trans('admin/hardware/form.redirect_to_all', ['type' => 'assets']),
                'item' => trans('admin/hardware/form.redirect_to_type', ['type' => trans('general.asset')]),
                'other_redirect' => trans('admin/hardware/form.redirect_to_type', [ 'type' => trans('general.asset').' '.trans('general.asset_model')]),
               ]
])


{{-- Page content --}}
@section('inputFields')

    @if (session('requires_ack_failed_tests'))
        <input type="hidden" name="ack_failed_tests" value="1">
    @endif

    {{-- Company selection hidden while the refurb fork runs single-company flows --}}
    @includeWhen(false, 'partials.forms.edit.company-select', ['translated_name' => trans('general.company'), 'fieldname' => 'company_id'])


  <!-- Asset Tag -->
  <div class="form-group {{ $errors->has('asset_tag') ? ' has-error' : '' }}">
    <label for="asset_tag" class="col-md-3 control-label">{{ trans('admin/hardware/form.tag') }}</label>



      @if  ($item->id)
          <!-- we are editing an existing asset,  there will be only one asset tag -->
          <div class="col-md-7 col-sm-12">
              @php
                  $assetTagOverrideActive = old('asset_tag_case_override.1', 0) ? true : false;
                  $assetTagReadOnly = !auth()->user()->isAdmin();
              @endphp
              <div class="js-case-wrapper" data-case-field="asset_tag">
                  <div class="input-group">
                      <input class="form-control js-asset-tag-input js-uppercase-input" type="text" name="asset_tags[1]" id="asset_tag" value="{{ old('asset_tag', $item->asset_tag) }}" @unless(auth()->user()->isAdmin()) readonly @endunless>
                      <span class="input-group-btn">
                          <button type="button" class="btn {{ $assetTagOverrideActive ? 'btn-warning active' : 'btn-default' }} js-case-override-toggle" aria-pressed="{{ $assetTagOverrideActive ? 'true' : 'false' }}" title="Preserve case" {{ $assetTagReadOnly ? 'disabled' : '' }}>
                              Aa
                          </button>
                      </span>
                  </div>
                  <input type="hidden" name="asset_tag_case_override[1]" class="js-case-override-input" value="{{ $assetTagOverrideActive ? '1' : '0' }}">
              </div>
              {!! $errors->first('asset_tags', '<span class="alert-msg"><i class="fas fa-times"></i> :message</span>') !!}
              {!! $errors->first('asset_tag', '<span class="alert-msg"><i class="fas fa-times"></i> :message</span>') !!}
          </div>
      @else
          <!-- we are creating a new asset - asset tag is auto-generated by default but editable -->
          <div class="col-md-7 col-sm-8">
              @php
                  $assetTagOverrideActive = old('asset_tag_case_override.1', 0) ? true : false;
              @endphp
              <div class="js-case-wrapper" data-case-field="asset_tag">
                  <div class="input-group">
                      <input class="form-control js-asset-tag-input js-uppercase-input" type="text" name="asset_tags[1]" id="asset_tag" value="{{ old('asset_tags.1', \App\Models\Asset::generateTag()) }}" readonly>
                      <span class="input-group-btn">
                          <button type="button" class="btn btn-default js-asset-tag-unlock">Unlock</button>
                          <button type="button" class="btn {{ $assetTagOverrideActive ? 'btn-warning active' : 'btn-default' }} js-case-override-toggle" aria-pressed="{{ $assetTagOverrideActive ? 'true' : 'false' }}" title="Preserve case">
                              Aa
                          </button>
                      </span>
                  </div>
                  <input type="hidden" name="asset_tag_case_override[1]" class="js-case-override-input" value="{{ $assetTagOverrideActive ? '1' : '0' }}">
              </div>
              {!! $errors->first('asset_tags', '<span class="alert-msg"><i class="fas fa-times"></i> :message</span>') !!}
              {!! $errors->first('asset_tag', '<span class="alert-msg"><i class="fas fa-times"></i> :message</span>') !!}
          </div>
      @endif
  </div>

    @include ('partials.forms.edit.serial', [
        'fieldname'=> 'serials[1]',
        'old_val_name' => 'serials.1',
        'translated_serial' => trans('admin/hardware/form.serial'),
        'show_duplicate_warning' => true,
        'serial_index' => 1,
        'show_case_override' => true,
        'case_override_name' => 'serial_case_override',
    ])

    <div class="input_fields_wrap">
    </div>

    @php
        $selected_category = old('category_id');
        $selected_manufacturer = old('manufacturer_id');
        if (!$selected_category && $item->model) {
            $selected_category = $item->model->category_id;
        }
        if (!$selected_manufacturer && $item->model) {
            $selected_manufacturer = $item->model->manufacturer_id;
        }
    @endphp

    @include('partials.forms.edit.category-select', ['translated_name' => trans('general.category'), 'fieldname' => 'category_id', 'selected' => $selected_category])
    @if (false && $item->id)
        @include('partials.forms.edit.manufacturer-select', ['translated_name' => trans('general.manufacturer'), 'fieldname' => 'manufacturer_id', 'selected' => $selected_manufacturer])
    @endif
    @include('partials.forms.edit.model-select', [
        'translated_name' => trans('admin/hardware/form.model'),
        'fieldname' => 'model_id',
        'hide_new' => !$item->id,
    ])
    @include ('partials.forms.edit.status', ['required' => false])

    <div id="model_spec_content">
        @include('hardware.partials.spec-overrides', [
            'attributes' => $specAttributes ?? collect(),
            'modelNumbers' => $modelNumbers ?? collect(),
            'selectedModelNumber' => $selectedModelNumber ?? null,
        ])
    </div>
    @if (false && !$item->id)
        @include ('partials.forms.checkout-selector', ['user_select' => 'true','asset_select' => 'true', 'location_select' => 'true', 'style' => 'display:none;'])
        @include ('partials.forms.edit.user-select', ['translated_name' => trans('admin/hardware/form.checkout_to'), 'fieldname' => 'assigned_user', 'style' => 'display:none;', 'required' => 'false'])
        @include ('partials.forms.edit.asset-select', ['translated_name' => trans('admin/hardware/form.checkout_to'), 'fieldname' => 'assigned_asset', 'style' => 'display:none;', 'required' => 'false'])
        @include ('partials.forms.edit.location-cascade-select', ['translated_name' => trans('admin/hardware/form.checkout_to'), 'fieldname' => 'assigned_location', 'style' => 'display:none;', 'required' => 'false'])
    @endif

    @include ('partials.forms.edit.notes')
    @include ('partials.forms.edit.location-cascade-select', ['translated_name' => trans('admin/hardware/form.default_location'), 'fieldname' => 'rtd_location_id', 'help_text' => trans('general.rtd_location_help')])
    <div class="form-group">
        <div class="col-md-7 col-md-offset-3">
            <label class="form-control">
                <input type="checkbox" value="1" name="use_custom_location" id="use_custom_location" {{ old('use_custom_location', $item->location_note ? 1 : 0) ? 'checked="checked"' : '' }} aria-label="use_custom_location">
                {{ trans('admin/hardware/form.use_custom_location') }}
            </label>
        </div>
    </div>
    <div id="location_note_group" class="form-group{{ $errors->has('location_note') ? ' has-error' : '' }}">
        <label for="location_note" class="col-md-3 control-label">{{ trans('admin/hardware/form.location_note') }}</label>
        <div class="col-md-7 col-sm-12">
            <textarea class="form-control" name="location_note" id="location_note" {{ old('use_custom_location', $item->location_note ? 1 : 0) ? '' : 'disabled="disabled"' }}>{{ old('location_note', $item->location_note) }}</textarea>
            {!! $errors->first('location_note', '<span class="alert-msg"><i class="fas fa-times"></i> :message</span>') !!}
            <p class="help-block">{{ trans('admin/hardware/form.location_note_help') }}</p>
        </div>
    </div>
    <script nonce="{{ csrf_token() }}">
        document.addEventListener('DOMContentLoaded', function () {
            const customCheck = document.getElementById('use_custom_location');
            const cascadeDiv = document.getElementById('rtd_location_id');
            const hiddenLoc = document.getElementById('rtd_location_id_id');
            const noteField = document.getElementById('location_note');
            function toggleCustom() {
                if (customCheck.checked) {
                    cascadeDiv.style.display = 'none';
                    hiddenLoc.disabled = true;
                    noteField.removeAttribute('disabled');
                } else {
                    cascadeDiv.style.display = '';
                    hiddenLoc.disabled = false;
                    noteField.setAttribute('disabled', 'disabled');
                }
            }
            customCheck.addEventListener('change', toggleCustom);
            toggleCustom();
        });
    </script>

    <div class="form-group">
        <div class="col-md-7 col-md-offset-3">
            <label class="form-control">
                <input type="hidden" name="is_sellable" value="0">
                <input type="checkbox" name="is_sellable" value="1" {{ old('is_sellable', $item->is_sellable) ? 'checked="checked"' : '' }} aria-label="is_sellable">
                {{ trans('admin/hardware/general.available_for_sale') }}
            </label>
            <p class="help-block">{{ trans('admin/hardware/general.available_for_sale_help') }}</p>
        </div>
    </div>



    @include ('partials.forms.edit.image-upload', ['image_path' => app('assets_upload_path')])


    <div id='custom_fields_content'>
        <!-- Custom Fields -->
        @if ($item->model && $item->model->fieldset)
        <?php $model = $item->model; ?>
        @endif
        @if (old('model_id'))
            @php
                $model = \App\Models\AssetModel::find(old('model_id'));
            @endphp
        @elseif (isset($selected_model))
            @php
                $model = $selected_model;
            @endphp
        @endif
        @if (isset($model) && $model)
        @include("models/custom_fields_form",["model" => $model])
        @endif
    </div>


        <div class="col-md-12 col-sm-12">

        <fieldset name="optional-details">

            <legend class="highlight">
                <a id="optional_info">
                    <x-icon type="caret-right" id="optional_info_icon" />
                    {{ trans('admin/hardware/form.optional_infos') }}
                </a>
            </legend>

            <div id="optional_details" class="col-md-12" style="display:none">
                @include ('partials.forms.edit.name', ['translated_name' => trans('admin/hardware/form.name')])
                @include ('partials.forms.edit.warranty')
                @include ('partials.forms.edit.datepicker', ['translated_name' => trans('admin/hardware/form.expected_checkin'),'fieldname' => 'expected_checkin'])
                @include ('partials.forms.edit.datepicker', ['translated_name' => trans('general.next_audit_date'),'fieldname' => 'next_audit_date', 'help_text' => trans('general.next_audit_date_help')])
                <!-- byod checkbox -->
                <div class="form-group byod">
                    <div class="col-md-7 col-md-offset-3">
                        <label class="form-control">
                            <input type="checkbox" value="1" name="byod" {{ (old('remote', $item->byod)) == '1' ? ' checked="checked"' : '' }} aria-label="byod">
                            {{ trans('general.byod') }}
                        </label>
                        <p class="help-block">
                            {{ trans('general.byod_help') }}
                        </p>
                    </div>
                </div>

            </div> <!-- end optional details -->
        </fieldset>

        </div><!-- end col-md-12 col-sm-12-->



        <div class="col-md-12 col-sm-12">
            <fieldset name="order-info">
                <legend class="highlight">
                    <a id="order_info">
                        <x-icon type="caret-right" id="order_info_icon" />
                        {{ trans('admin/hardware/form.order_details') }}
                    </a>
                </legend>

                <div id='order_details' class="col-md-12" style="display:none">
                    @include ('partials.forms.edit.order_number')
                    @include ('partials.forms.edit.datepicker', ['translated_name' => trans('general.purchase_date'),'fieldname' => 'purchase_date'])
                    @include ('partials.forms.edit.datepicker', ['translated_name' => trans('admin/hardware/form.eol_date'),'fieldname' => 'asset_eol_date'])
                    @include ('partials.forms.edit.supplier-select', ['translated_name' => trans('general.supplier'), 'fieldname' => 'supplier_id'])

                    @php
                        $currency_type = null;
                        if ($item->id && $item->location) {
                            $currency_type = $item->location->currency;
                        }
                    @endphp

                    @include ('partials.forms.edit.purchase_cost', ['currency_type' => $currency_type])

                </div> <!-- end order details -->
            </fieldset>
        </div><!-- end col-md-12 col-sm-12-->
    </div><!-- end col-md-12 col-sm-12-->
    </div><!-- end col-md-12 col-sm-12-->

    @php
        $testSummary = $testSummary ?? ['missing_run' => false, 'failed' => collect(), 'incomplete' => collect(), 'run' => null];
        $testIssuesPresent = $testSummary['missing_run'] || $testSummary['failed']->isNotEmpty() || $testSummary['incomplete']->isNotEmpty();
        $confirmStatusIds = collect($statuslabel_list ?? [])->filter(function ($label) {
            $name = strtolower(trim((string) $label));
            if (strpos($name, 'ready for sale') !== false) {
                return true;
            }
            if ($name === 'sold' || str_starts_with($name, 'sold ')) {
                return true;
            }
            return false;
        })->keys()->values();
    @endphp

    @if ($testIssuesPresent)
        <div class="modal fade" id="tests-status-confirm-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="{{ trans('general.close') }}">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">{{ trans('tests.status_change_warning') }}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{{ trans('tests.status_change_prompt') }}</p>
                        <ul>
                            @if ($testSummary['missing_run'])
                                <li>{{ trans('tests.no_test_run_recorded') }}</li>
                            @endif
                            @if ($testSummary['failed']->isNotEmpty())
                                <li>{{ trans('tests.failed_list', ['tests' => $testSummary['failed']->implode(', ')]) }}</li>
                            @endif
                            @if ($testSummary['incomplete']->isNotEmpty())
                                <li>{{ trans('tests.incomplete_list', ['tests' => $testSummary['incomplete']->implode(', ')]) }}</li>
                            @endif
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('general.cancel') }}</button>
                        <button type="button" class="btn btn-warning" id="tests-status-confirm-yes">{{ trans('general.confirm') }}</button>
                    </div>
                </div>
            </div>
        </div>
    @endif
   
@stop

@section('moar_scripts')



<script nonce="{{ csrf_token() }}">

    @if(Request::has('model_id'))
        //TODO: Refactor custom fields to use Livewire, populate from server on page load when requested with model_id
    $(document).ready(function() {
        fetchCustomFields();
        var initialContext = getModelSelectionContext();
        fetchSpecification(initialContext.modelId, initialContext.modelNumberId || $('#model_number_id').val());
    });
    @endif

    var transformed_oldvals={};
    var transformed_spec_vals={};

    function getModelSelectionContext() {
        var rawValue = $('#model_select_id').val();
        if (!rawValue) {
            return { modelId: null, modelNumberId: null };
        }

        var parts = String(rawValue).split(':');
        if (parts.length === 2) {
            return { modelId: parts[0], modelNumberId: parts[1] };
        }

        return { modelId: rawValue, modelNumberId: null };
    }

    function fetchCustomFields() {
        //save custom field choices
        var oldvals = $('#custom_fields_content').find('input,select,textarea').serializeArray();
        for(var i in oldvals) {
            transformed_oldvals[oldvals[i].name]=oldvals[i].value;
        }

        var context = getModelSelectionContext();
        var modelid = context.modelId;
        if (!modelid) {
            $('#custom_fields_content').html("");
        } else {

            $.ajax({
                type: 'GET',
                url: "{{ config('app.url') }}/models/" + modelid + "/custom_fields",
                headers: {
                    "X-Requested-With": 'XMLHttpRequest',
                    "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
                },
                _token: "{{ csrf_token() }}",
                dataType: 'html',
                success: function (data) {
                    $('#custom_fields_content').html(data);
                    $('#custom_fields_content select').select2(); //enable select2 on any custom fields that are select-boxes
                    //now re-populate the custom fields based on the previously saved values
                    $('#custom_fields_content').find('input,select,textarea').each(function (index,elem) {
                        if(transformed_oldvals[elem.name]) {
                            if (elem.type === 'checkbox' || elem.type === 'radio'){
                                let shouldBeChecked = oldvals.find(oldValElement => {
                                    return oldValElement.name === elem.name && oldValElement.value === $(elem).val();
                                });

                                if (shouldBeChecked){
                                    $(elem).prop('checked', true);
                                }

                                return;
                            }
                             {{-- If there already *is* is a previously-input 'transformed_oldvals' handy,
                                  overwrite with that previously-input value *IF* this is an edit of an existing item *OR*
                                  if there is no new default custom field value coming from the model --}}
                            if({{ $item->id ? 'true' : 'false' }} || $(elem).val() == '') {
                                $(elem).val(transformed_oldvals[elem.name]).trigger('change'); //the trigger is for select2-based objects, if we have any
                            }
                        }

                    });
                }
            });
        }
    }

    window.fetchSpecification = function(modelId, modelNumberId) {
        var specContainer = $('#model_spec_content');
        transformed_spec_vals = {};
        specContainer.find('input,select,textarea').each(function () {
            transformed_spec_vals[this.name] = $(this).val();
        });

        if (!modelId) {
            specContainer.html('');
            return;
        }

        var requestData = {};
        var assetId = {{ $item->id ?? 'null' }};
        if (assetId) {
            requestData.asset_id = assetId;
        }
        if (modelNumberId) {
            requestData.model_number_id = modelNumberId;
        }

        $.ajax({
            type: 'GET',
            url: "{{ config('app.url') }}/models/" + modelId + "/spec-form",
            headers: {
                "X-Requested-With": 'XMLHttpRequest'
            },
            data: requestData,
            dataType: 'html',
            success: function (html) {
                specContainer.html(html);
                specContainer.find('input,select,textarea').each(function () {
                    if (typeof transformed_spec_vals[this.name] !== 'undefined' && transformed_spec_vals[this.name] !== '') {
                        $(this).val(transformed_spec_vals[this.name]);
                    }
                });
            }
        });
    }

    function user_add(status_id) {

        if (status_id != '') {
            $(".status_spinner").css("display", "inline");
            $.ajax({
                url: "{{config('app.url') }}/api/v1/statuslabels/" + status_id + "/deployable",
                headers: {
                    "X-Requested-With": 'XMLHttpRequest',
                    "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
                },
                success: function (data) {
                    $(".status_spinner").css("display", "none");
                    $("#selected_status_status").fadeIn();

                    if (data == true) {
                        $("#assignto_selector").show();
                        $("#assigned_user").show();

                        $("#selected_status_status").removeClass('text-danger');
                        $("#selected_status_status").addClass('text-success');
                        $("#selected_status_status").html('<x-icon type="checkmark" /> {{ trans('admin/hardware/form.asset_deployable')}}');


                    } else {
                        $("#assignto_selector").hide();
                        $("#selected_status_status").removeClass('text-success');
                        $("#selected_status_status").addClass('text-danger');
                        $("#selected_status_status").html('<x-icon type="warning" /> {{ (($item->assigned_to!='') && ($item->assigned_type!='') && ($item->deleted_at == '')) ? trans('admin/hardware/form.asset_not_deployable_checkin') : trans('admin/hardware/form.asset_not_deployable')  }} ');
                    }
                }
            });
        }
    }

    var serialCheckEndpoint = '/api/v1/hardware/serial-check';
    var serialCheckAssetId = {{ $item->id ?? 'null' }};
    var serialCheckRequests = {};
    var serialCheckTimers = {};

    function setSerialWarning($entry, payload) {
        var $warning = $entry.find('.js-serial-warning');
        if (!$warning.length) {
            return;
        }

        var $details = $entry.find('.js-serial-warning-details');
        var $allow = $entry.find('.js-serial-allow');

        if (!payload || !payload.exists) {
            $warning.addClass('hidden');
            $details.empty();
            if ($allow.length) {
                $allow.prop('checked', false);
                $allow.prop('disabled', true);
            }
            return;
        }

        $warning.removeClass('hidden');
        $details.empty();

        var count = payload.count || 0;
        var assets = payload.assets || [];
        var summary = $('<div class="serial-duplicate-summary"></div>')
            .text('Used by ' + count + ' asset' + (count === 1 ? '' : 's') + ':');
        var $list = $('<ul class="list-unstyled serial-duplicate-list"></ul>');

        assets.forEach(function (asset) {
            var label = '';
            if (asset.asset_tag) {
                label = asset.asset_tag;
            }
            if (asset.name) {
                label = label ? label + ' - ' + asset.name : asset.name;
            }
            if (!label && asset.id) {
                label = 'Asset #' + asset.id;
            }
            var $link = $('<a></a>').attr('href', '/hardware/' + asset.id).text(label);
            $list.append($('<li></li>').append($link));
        });

        if (count > assets.length) {
            $list.append($('<li></li>').text('+' + (count - assets.length) + ' more'));
        }

        $details.append(summary).append($list);

        if ($allow.length) {
            $allow.prop('disabled', false);
        }
    }

    function checkSerialInput($input) {
        var serial = $.trim($input.val());
        var $entry = $input.closest('.js-serial-entry');
        if (!serial) {
            setSerialWarning($entry, null);
            return;
        }

        var requestKey = $input.attr('name') || $input.attr('id') || serial;
        if (serialCheckRequests[requestKey]) {
            serialCheckRequests[requestKey].abort();
        }

        var data = { serial: serial };
        if (serialCheckAssetId) {
            data.ignore_id = serialCheckAssetId;
        }

        serialCheckRequests[requestKey] = $.ajax({
            type: 'GET',
            url: serialCheckEndpoint,
            data: data,
            headers: {
                "X-Requested-With": 'XMLHttpRequest',
                "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
            },
            success: function (payload) {
                if ($.trim($input.val()) !== serial) {
                    return;
                }
                setSerialWarning($entry, payload);
            },
            error: function () {
                setSerialWarning($entry, null);
            }
        });
    }

    function scheduleSerialCheck($input) {
        var key = $input.attr('name') || $input.attr('id') || 'serial';
        if (serialCheckTimers[key]) {
            clearTimeout(serialCheckTimers[key]);
        }
        serialCheckTimers[key] = setTimeout(function () {
            checkSerialInput($input);
        }, 300);
    }

    function unlockAssetTag($button) {
        var $input = $('.js-asset-tag-input');
        if (!$input.length) {
            return;
        }
        $input.prop('readonly', false).focus().select();
        if ($button && $button.length) {
            $button.prop('disabled', true).addClass('disabled').text('Unlocked');
        }
    }

    function applyUppercase($input) {
        if (!$input || !$input.length) {
            return;
        }
        var $wrapper = $input.closest('.js-case-wrapper');
        var overrideEnabled = $wrapper.find('.js-case-override-input').val() === '1';
        if (overrideEnabled) {
            return;
        }
        var value = $input.val();
        if (!value) {
            return;
        }
        var upper = value.toUpperCase();
        if (value !== upper) {
            $input.val(upper);
        }
    }

    function syncCaseOverrideState($wrapper) {
        var $toggle = $wrapper.find('.js-case-override-toggle');
        var $hidden = $wrapper.find('.js-case-override-input');
        if (!$toggle.length || !$hidden.length) {
            return;
        }
        var active = $hidden.val() === '1';
        $toggle.toggleClass('btn-warning active', active);
        $toggle.toggleClass('btn-default', !active);
        $toggle.attr('aria-pressed', active ? 'true' : 'false');
    }

    function toggleCaseOverride($button) {
        var $wrapper = $button.closest('.js-case-wrapper');
        var $hidden = $wrapper.find('.js-case-override-input');
        if (!$hidden.length) {
            return;
        }
        var active = $hidden.val() === '1';
        $hidden.val(active ? '0' : '1');
        syncCaseOverrideState($wrapper);
        if (active) {
            applyUppercase($wrapper.find('.js-uppercase-input'));
        }
    }


    $(function () {
        //grab specification and custom fields whenever the model changes.
        $('#model_select_id').on("change", function () {
            var context = getModelSelectionContext();
            var hiddenSelector = $(this).data('hidden-input');
            if (hiddenSelector) {
                $(hiddenSelector).val(context.modelId || '');
            }
            fetchCustomFields();
            fetchSpecification(context.modelId, context.modelNumberId);
        });

        fetchCustomFields();
        var initialSelection = getModelSelectionContext();
        fetchSpecification(initialSelection.modelId, initialSelection.modelNumberId || $('#model_number_id').val());

        //initialize assigned user/loc/asset based on statuslabel's statustype
        user_add($(".status_id option:selected").val());

        //whenever statuslabel changes, update assigned user/loc/asset
        $(".status_id").on("change", function () {
            user_add($(".status_id").val());
        });

    });


    // Add another asset tag + serial combination if the plus sign is clicked
    $(document).ready(function() {

        var max_fields      = 100; //maximum input boxes allowed
        var wrapper         = $(".input_fields_wrap"); //Fields wrapper
        var add_button      = $(".add_field_button"); //Add button ID
        var x               = 1; //initial text box count




        $(add_button).click(function(e){ //on add input button click

            e.preventDefault();

            var prefixPattern = '{{ preg_quote(App\Models\Setting::getSettings()->auto_increment_prefix, '/') }}';
            var raw_tag = String($("#asset_tag").val() || '');
            if (prefixPattern) {
                raw_tag = raw_tag.replace(new RegExp('^' + prefixPattern, 'i'), '');
            }
            var parsed_tag = parseInt(raw_tag, 10);
            var box_html        = '';
			const zeroPad 		= (num, places) => String(num).padStart(places, '0');

            // Check that we haven't exceeded the max number of asset fields
            if (x < max_fields) {

                var auto_tag = '';
                if (raw_tag !== '' && !isNaN(parsed_tag)) {
                     auto_tag = zeroPad(parsed_tag + parseInt(x), raw_tag.length);
                }

                x++; //text box increment

                box_html += '<span class="fields_wrapper">';
                box_html += '<div class="form-group"><label for="asset_tag" class="col-md-3 control-label">{{ trans('admin/hardware/form.tag') }} ' + x + '</label>';
                box_html += '<div class="col-md-7 col-sm-12">';
                box_html += '<div class="js-case-wrapper" data-case-field="asset_tag">';
                box_html += '<div class="input-group">';
                box_html += '<input type="text" class="form-control js-uppercase-input" name="asset_tags[' + x + ']" value="{{ (($snipeSettings->auto_increment_prefix!='') && ($snipeSettings->auto_increment_assets=='1')) ? $snipeSettings->auto_increment_prefix : '' }}'+ auto_tag +'">';
                box_html += '<span class="input-group-btn">';
                box_html += '<button type="button" class="btn btn-default js-case-override-toggle" aria-pressed="false" title="Preserve case">Aa</button>';
                box_html += '</span>';
                box_html += '</div>';
                box_html += '<input type="hidden" name="asset_tag_case_override[' + x + ']" class="js-case-override-input" value="0">';
                box_html += '</div>';
                box_html += '</div>';
                box_html += '<div class="col-md-2 col-sm-12">';
                box_html += '<a href="#" class="remove_field btn btn-default btn-sm"><x-icon type="minus" /></a>';
                box_html += '</div>';
                box_html += '</div>';
                box_html += '<div class="form-group js-serial-entry" data-serial-index="' + x + '"><label for="serial" class="col-md-3 control-label">{{ trans('admin/hardware/form.serial') }} ' + x + '</label>';
                box_html += '<div class="col-md-7 col-sm-12">';
                box_html += '<div class="js-case-wrapper" data-case-field="serial">';
                box_html += '<div class="input-group">';
                box_html += '<input type="text" class="form-control js-serial-input js-uppercase-input" name="serials[' + x + ']">';
                box_html += '<span class="input-group-btn">';
                box_html += '<button type="button" class="btn btn-default js-case-override-toggle" aria-pressed="false" title="Preserve case">Aa</button>';
                box_html += '</span>';
                box_html += '</div>';
                box_html += '<input type="hidden" name="serial_case_override[' + x + ']" class="js-case-override-input" value="0">';
                box_html += '</div>';
                box_html += '</div>';
                box_html += '<div class="col-md-7 col-sm-12 col-md-offset-3">';
                box_html += '<div class="alert alert-warning serial-duplicate-warning hidden js-serial-warning" role="alert">';
                box_html += '<strong>Serial already in use.</strong>';
                box_html += '<div class="serial-duplicate-details js-serial-warning-details"></div>';
                box_html += '<label class="serial-duplicate-override">';
                box_html += '<input type="checkbox" name="allow_duplicate_serials[' + x + ']" class="js-serial-allow" value="1" disabled> Allow duplicate serial';
                box_html += '</label>';
                box_html += '</div>';
                box_html += '</div>';
                box_html += '</div>';
                box_html += '</span>';
                var $newFields = $(box_html);
                $(wrapper).append($newFields);
                $newFields.find('.js-case-wrapper').each(function () {
                    syncCaseOverrideState($(this));
                    $(this).find('.js-uppercase-input').each(function () {
                        applyUppercase($(this));
                    });
                });

            // We have reached the maximum number of extra asset fields, so disable the button
            } else {
                $(".add_field_button").attr('disabled');
                $(".add_field_button").addClass('disabled');
            }
        });

        $(wrapper).on("click",".remove_field", function(e){ //user clicks on remove text
            $(".add_field_button").removeAttr('disabled');
            $(".add_field_button").removeClass('disabled');
            e.preventDefault();
            //console.log(x);

            $(this).parent('div').parent('div').parent('span').remove();
            x--;
        });


        $('.expand').click(function(){
            id = $(this).attr('id');
            fields = $(this).text();
            if (txt == '+'){
                $(this).text('-');
            }
            else{
                $(this).text('+');
            }
            $("#"+id).toggle();

        });

        {{-- TODO: Clean up some of the duplication in here. Not too high of a priority since we only copied it once. --}}
        $("#optional_info").on("click",function(){
            $('#optional_details').fadeToggle(100);
            $('#optional_info_icon').toggleClass('fa-caret-right fa-caret-down');
            var optional_info_open = $('#optional_info_icon').hasClass('fa-caret-down');
            document.cookie = "optional_info_open="+optional_info_open+'; path=/';
        });

        $("#order_info").on("click",function(){
            $('#order_details').fadeToggle(100);
            $("#order_info_icon").toggleClass('fa-caret-right fa-caret-down');
            var order_info_open = $('#order_info_icon').hasClass('fa-caret-down');
            document.cookie = "order_info_open="+order_info_open+'; path=/';
        });

        var all_cookies = document.cookie.split(';')
        for(var i in all_cookies) {
            var trimmed_cookie = all_cookies[i].trim(' ')
            if (trimmed_cookie.startsWith('optional_info_open=')) {
                elems = all_cookies[i].split('=', 2)
                if (elems[1] == 'true') {
                    $('#optional_info').trigger('click')
                }
            }
            if (trimmed_cookie.startsWith('order_info_open=')) {
                elems = all_cookies[i].split('=', 2)
                if (elems[1] == 'true') {
                    $('#order_info').trigger('click')
                }
            }
        }

    });

    $(document).ready(function() {
        $(document).on('click', '.js-case-override-toggle', function (e) {
            e.preventDefault();
            toggleCaseOverride($(this));
        });

        $(document).on('input', '.js-uppercase-input', function () {
            applyUppercase($(this));
        });

        $(document).on('click', '.js-asset-tag-unlock', function (e) {
            e.preventDefault();
            unlockAssetTag($(this));
        });

        $(document).on('input', '.js-serial-input', function () {
            applyUppercase($(this));
            scheduleSerialCheck($(this));
        });

        $(document).on('blur change', '.js-serial-input', function () {
            checkSerialInput($(this));
        });

        $('.js-case-wrapper').each(function () {
            syncCaseOverrideState($(this));
            $(this).find('.js-uppercase-input').each(function () {
                applyUppercase($(this));
            });
        });

        $('.js-serial-input').each(function () {
            applyUppercase($(this));
            if ($.trim($(this).val()) !== '') {
                checkSerialInput($(this));
            } else {
                setSerialWarning($(this).closest('.js-serial-entry'), null);
            }
        });
    });

    $(document).ready(function() {
        var categorySelect = $('#category_select_id');
        var manufacturerSelect = $('#manufacturer_select_id');
        var modelSelect = $('#model_select_id');

        manufacturerSelect.data('category-id', categorySelect.val());
        modelSelect.data('category-id', categorySelect.val());
        if (manufacturerSelect.val()) {
            modelSelect.data('manufacturer-id', manufacturerSelect.val());
        }
        categorySelect.on('change', function (e, preserve) {
            var categoryId = $(this).val();
            manufacturerSelect.data('category-id', categoryId);
            modelSelect.data('category-id', categoryId);
            if (preserve) {
                return;
            }
            manufacturerSelect.val(null).trigger('change');
            modelSelect.val(null).trigger('change');
        });

        manufacturerSelect.on('change', function (e, preserve) {
            var manufacturerId = $(this).val();
            modelSelect.data('manufacturer-id', manufacturerId);
            if (preserve) {
                return;
            }
            modelSelect.val(null).trigger('change');
        });

        function syncFromModel(model) {
            if (model.category && categorySelect.val() != model.category.id) {
                categorySelect.val(model.category.id).trigger('change', [true]);
            }
            if (model.manufacturer && manufacturerSelect.val() != model.manufacturer.id) {
                manufacturerSelect.val(model.manufacturer.id).trigger('change', [true]);
            }
        }

        modelSelect.on('change', function () {
            var context = getModelSelectionContext();
            if (context.modelId) {
                $.getJSON("{{ config('app.url') }}/api/v1/models/" + context.modelId, syncFromModel);
            }
        });
    });

    $(function () {
        var statusConfirm = {
            hasIssues: {{ $testIssuesPresent ? 'true' : 'false' }},
            statusIds: @json($confirmStatusIds->map(fn ($id) => (string) $id)->values()),
        };

        if (!statusConfirm.hasIssues) {
            return;
        }

        var form = document.getElementById('create-form');
        var statusSelect = document.getElementById('status_select_id');
        var modalEl = document.getElementById('tests-status-confirm-modal');
        var confirmBtn = document.getElementById('tests-status-confirm-yes');
        var redirectSelect = form ? form.querySelector('select[name="redirect_option"]') : null;
        var allowSubmit = false;

        if (!form || !statusSelect || !modalEl || !confirmBtn) {
            return;
        }

        var shouldConfirm = function () {
            var value = statusSelect.value || '';
            return statusConfirm.statusIds.includes(String(value));
        };

        form.addEventListener('submit', function (event) {
            if (allowSubmit || !shouldConfirm()) {
                return;
            }

            event.preventDefault();
            (window.jQuery || window.$)(modalEl).modal('show');
        });

        confirmBtn.addEventListener('click', function () {
            var ack = document.getElementById('ack_failed_tests');
            if (!ack) {
                ack = document.createElement('input');
                ack.type = 'hidden';
                ack.name = 'ack_failed_tests';
                ack.id = 'ack_failed_tests';
                form.appendChild(ack);
            }
            ack.value = '1';
            if (redirectSelect) {
                redirectSelect.value = 'item';
            }
            allowSubmit = true;
            (window.jQuery || window.$)(modalEl).modal('hide');
            if (typeof form.requestSubmit === 'function') {
                form.requestSubmit();
            } else {
                form.submit();
            }
        });
    });




</script>
@stop
