<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Image Driver
    |--------------------------------------------------------------------------
    |
    | Intervention Image uses PHP's GD Library to process images. Ensure the
    | GD extension is installed and enabled in your PHP configuration.
    |
    */

    'driver' => env('IMAGE_LIB', 'gd'),

];
