<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
*/


return [

    'Global' => [
        [
            'permission' => 'superuser',
            'label'      => 'Super User',
            'note'       => 'Determines whether the user has full access to all aspects of the admin. This setting overrides any more specific permissions throughout the system. ',
            'display'    => true,
        ],
    ],

    'Admin' => [
        [
            'permission' => 'admin',
            'label'      => '',
            'note'       => 'Determines whether the user has access to most aspects of the admin. ',
            'display'    => true,
        ],
    ],

    'CSV Import' => [
        [
            'permission' => 'import',
            'label'      => '',
            'note'       => 'This will allow users to import even if access to users, assets, etc is denied elsewhere.',
            'display'    => true,
        ],
    ],

    'Reports' => [
        [
            'permission' => 'reports.view',
            'label'      => 'View',
            'note'       => 'Determines whether the user has the ability to view reports.',
            'display'    => true,
        ],
    ],

    'Assets' => [
        [
            'permission' => 'assets.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'assets.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'assets.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'assets.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'assets.sale_transition',
            'label'      => 'Move Ready/Sold',
            'note'       => 'Allows the user to move assets into ready-for-sale and sold lifecycle statuses.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.images.upload',
            'label'      => 'Upload Images',
            'note'       => 'Allows the user to upload and caption asset images.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.images.manage',
            'label'      => 'Manage Images',
            'note'       => 'Allows the user to remove asset images.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.files.view',
            'label'      => 'View Files',
            'note'       => 'Allows the user to view and download private files attached to assets.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.files.upload',
            'label'      => 'Upload Files',
            'note'       => 'Allows the user to upload private files to assets.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.files.manage',
            'label'      => 'Manage Files',
            'note'       => 'Allows the user to delete private files attached to assets.',
            'display'    => true,
        ],
        [
            'permission' => 'assets.view.encrypted_custom_fields',
            'label'      => 'View and Modify Encrypted Custom Fields',
            'note'       => '',
            'display'    => true,
        ],

    ],

    'Accessories' => [
        [
            'permission' => 'accessories.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.edit',
            'label'      => 'Edit ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.checkout',
            'label'      => 'Checkout ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.checkin',
            'label'      => 'Checkin ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'accessories.files',
            'label'      => 'View and Modify Accessory Files',
            'note'       => '',
            'display'    => true,
        ],

    ],

    'Consumables' => [
        [
            'permission' => 'consumables.view',
            'label'      => 'View',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'consumables.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'consumables.edit',
            'label'      => 'Edit ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'consumables.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'consumables.checkout',
            'label'      => 'Checkout ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'consumables.files',
            'label'      => 'View and Modify Consumable Files',
            'note'       => '',
            'display'    => true,
        ],
    ],


    'Licenses' => [
        [
            'permission' => 'licenses.view',
            'label'      => 'View',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.edit',
            'label'      => 'Edit ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.checkout',
            'label'      => 'Checkout ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.checkin',
            'label'      => 'Checkin ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.keys',
            'label'      => 'View License Keys',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'licenses.files',
            'label'      => 'View and Modify License Files',
            'note'       => '',
            'display'    => true,
        ],
    ],


    'Components' => [
        [
            'permission' => 'components.view',
            'label'      => 'View',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.update',
            'label'      => 'Update ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.extract',
            'label'      => 'Extract ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.install',
            'label'      => 'Install ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.move',
            'label'      => 'Move ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.verify',
            'label'      => 'Verify ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.destroy',
            'label'      => 'Destroy',
            'note'       => 'Mark tracked components for destruction and record irreversible destruction.',
            'display'    => true,
        ],
        [
            'permission' => 'components.manage_definitions',
            'label'      => 'Manage Definitions',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'components.manage_definition_lifecycle',
            'label'      => 'Manage Definition Lifecycle',
            'note'       => 'Allows activating, deactivating, and removing saved definition contributions or expected subcomponents.',
            'display'    => true,
        ],
        [
            'permission' => 'components.manage_storage_locations',
            'label'      => 'Manage Storage',
            'note'       => '',
            'display'    => true,
        ],

    ],

    'Work Orders' => [
        [
            'permission' => 'workorders.view',
            'label'      => 'View',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'workorders.create',
            'label'      => 'Create',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'workorders.update',
            'label'      => 'Update',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'workorders.manage_visibility',
            'label'      => 'Manage Visibility',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Portal' => [
        [
            'permission' => 'portal.view',
            'label'      => 'View Portal',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Kits' => [
        [
            'permission' => 'kits.view',
            'label'      => 'View ',
            'note'       => 'Compatibility templates only; kit checkout is outside the refurbishment V1 contract.',
            'display'    => true,
        ],
        [
            'permission' => 'kits.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'kits.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'kits.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Users' => [
        [
            'permission' => 'users.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'users.create',
            'label'      => 'Create Users',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'users.edit',
            'label'      => 'Edit Users',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'users.delete',
            'label'      => 'Delete Users',
            'note'       => '',
            'display'    => true,
        ],

    ],

    'Models' => [
        [
            'permission' => 'models.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'models.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'models.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'models.manage_lifecycle',
            'label'      => 'Manage Model Lifecycle',
            'note'       => 'Allows changing the primary/default model number and deprecating or restoring model numbers.',
            'display'    => true,
        ],
        [
            'permission' => 'models.manage_specification_cleanup',
            'label'      => 'Clean Up Model Specifications',
            'note'       => 'Allows removing saved model-number attributes and expected-component rows, including affected asset overrides.',
            'display'    => true,
        ],
        [
            'permission' => 'models.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'models.files.view',
            'label'      => 'View Model Files',
            'note'       => 'Allows the user to view model-level files exposed as model resources.',
            'display'    => true,
        ],
        [
            'permission' => 'models.files.upload',
            'label'      => 'Upload Model Files',
            'note'       => 'Allows the user to upload model-level files.',
            'display'    => true,
        ],
        [
            'permission' => 'models.files.manage',
            'label'      => 'Manage Model Files',
            'note'       => 'Allows the user to delete model-level files.',
            'display'    => true,
        ],

    ],

    'Catalog Attributes' => [
        [
            'permission' => 'attributes.view',
            'label'      => 'View Attributes',
            'note'       => 'Allows viewing reusable catalog attribute definitions.',
            'display'    => true,
        ],
        [
            'permission' => 'attributes.create',
            'label'      => 'Create Attributes',
            'note'       => 'Allows creating reusable catalog attribute definitions and their initial options.',
            'display'    => true,
        ],
        [
            'permission' => 'attributes.edit',
            'label'      => 'Edit Attributes',
            'note'       => 'Allows editing attribute definitions and adding or updating options.',
            'display'    => true,
        ],
        [
            'permission' => 'attributes.lifecycle',
            'label'      => 'Manage Attribute Lifecycle',
            'note'       => 'Allows hiding, restoring, and removing saved attribute options.',
            'display'    => true,
        ],
        [
            'permission' => 'attributes.delete',
            'label'      => 'Delete Attributes',
            'note'       => 'Allows archiving attribute definitions that are not in use.',
            'display'    => true,
        ],
    ],

    'Categories' => [
        [
            'permission' => 'categories.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'categories.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'categories.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'categories.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Departments' => [
        [
            'permission' => 'departments.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'departments.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'departments.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'departments.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Status Labels' => [
        [
            'permission' => 'statuslabels.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'statuslabels.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'statuslabels.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'statuslabels.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Custom Fields' => [
        [
            'permission' => 'customfields.view',
            'label'      => 'View',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'customfields.create',
            'label'      => 'Create',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'customfields.edit',
            'label'      => 'Edit',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'customfields.delete',
            'label'      => 'Delete',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Suppliers' => [
        [
            'permission' => 'suppliers.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'suppliers.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'suppliers.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'suppliers.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],


    'Manufacturers' => [
        [
            'permission' => 'manufacturers.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'manufacturers.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'manufacturers.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'manufacturers.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Depreciations' => [
        [
            'permission' => 'depreciations.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'depreciations.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'depreciations.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'depreciations.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Locations' => [
        [
            'permission' => 'locations.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'locations.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'locations.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'locations.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Companies' => [
        [
            'permission' => 'companies.view',
            'label'      => 'View ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'companies.create',
            'label'      => 'Create ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'companies.edit',
            'label'      => 'Edit  ',
            'note'       => '',
            'display'    => true,
        ],
        [
            'permission' => 'companies.delete',
            'label'      => 'Delete ',
            'note'       => '',
            'display'    => true,
        ],
    ],

    'Scanning' => [
        [
            'permission' => 'scanning',
            'label'      => 'Use Scanner',
            'note'       => 'Allows the user to scan assets.',
            'display'    => true,
        ],
    ],

    'Testing' => [
        [
            'permission' => 'tests.execute',
            'label'      => 'Execute Tests',
            'note'       => 'Allows the user to run system tests.',
            'display'    => true,
        ],
        [
            'permission' => 'tests.delete',
            'label'      => 'Delete Tests',
            'note'       => 'Allows the user to remove test runs.',
            'display'    => true,
        ],
    ],

    'Workflow Configuration' => [
        [
            'permission' => 'workflows.view',
            'label'      => 'View Workflow Configuration',
            'note'       => 'Allows viewing workflow items and profiles.',
            'display'    => true,
        ],
        [
            'permission' => 'workflows.create',
            'label'      => 'Create Workflow Configuration',
            'note'       => 'Allows creating workflow items and profiles.',
            'display'    => true,
        ],
        [
            'permission' => 'workflows.edit',
            'label'      => 'Edit Workflow Configuration',
            'note'       => 'Allows editing and ordering workflow items, profiles, and profile composition.',
            'display'    => true,
        ],
        [
            'permission' => 'workflows.delete',
            'label'      => 'Delete Workflow Configuration',
            'note'       => 'Allows deleting workflow items and profiles.',
            'display'    => true,
        ],
    ],

    'Audits' => [
        [
            'permission' => 'audits.view',
            'label'      => 'View Audits',
            'note'       => 'Allows the user to view audit logs.',
            'display'    => true,
        ],
    ],

    'Configuration' => [
        [
            'permission' => 'config.manage',
            'label'      => 'Manage Configuration',
            'note'       => 'Allows the user to modify system configuration.',
            'display'    => true,
        ],
        [
            'permission' => 'config.qr_tooltips',
            'label'      => 'Configure QR & Tooltips',
            'note'       => 'Allows the user to manage QR code and tooltip settings.',
            'display'    => true,
        ],
    ],

    'Self' => [
        [
            'permission' => 'self.two_factor',
            'label'      => 'Two-Factor Authentication',
            'note'       => 'The user may disable/enable two-factor authentication themselves if two-factor is enabled and set to selective.',
            'display'    => true,
        ],

        [
            'permission' => 'self.api',
            'label'      => 'Create API Keys',
            'note'       => 'The user create personal API keys to utilize the REST API.',
            'display'    => true,
        ],

        [
            'permission' => 'self.edit_location',
            'label'      => 'Profile Edit Location',
            'note'       => 'The user may update their own location in their profile. Note that this is not affected by any additional Users permissions you grant to this user or group.',
            'display'    => true,
        ],

        [
            'permission' => 'self.view_purchase_cost',
            'label'      => 'View Purchase-Cost Column',
            'note'       => 'This user can see the purchase cost column of items assigned to them.',
            'display'    => true,
        ],

    ],

];
