<?php

return [
    'default' => 'dymo-s0929120-25x25',
    'enable_ui' => true,
    'print_queue' => env('LABEL_PRINTER_QUEUE'),
    'print_command' => env('LABEL_PRINT_COMMAND', 'lp'),
    'print_options' => array_values(array_filter(preg_split('/\s+/', env('LABEL_PRINT_OPTIONS', '')))),
    'queues' => array_values(array_filter(array_map('trim', explode(',', env('LABEL_PRINTER_QUEUES', ''))))),
    'templates' => [
        'dymo-99010-89x28' => [
            'name' => 'Dymo 99010 (89 x 28 mm) - Standard Address',
            'width_mm' => 89,
            'height_mm' => 28,
            'qr_size' => 220,
            'padding_mm' => 1.5,
            'qr_column_mm' => 42,
            'caption_font_size' => 8,
            'caption_lines' => 4,
            'caption_wrap' => 28,
        ],
        'dymo-s0929120-25x25' => [
            'name' => 'Dymo S0929120 (25 x 25 mm) - Multipurpose Square',
            'width_mm' => 25,
            'height_mm' => 25,
            'qr_size' => 224,
            'padding_mm' => 1.8,
            'qr_left_mm' => 3.2,
            'text_left_mm' => 1.8,
            'qr_column_mm' => 25,
            'caption_font_size' => 4,
            'caption_line_height' => 1.0,
            'caption_lines' => 1,
            'caption_wrap' => 40,
            'layout' => 'square-stack',
            'qr_box_mm' => 19,
            'text_height_mm' => 3,
            'text_gap_mm' => 0.3,
        ],
    ],
];
