<?php

return [
    'default' => 'dymo-99010-89x36',
    'enable_ui' => true,
    'print_queue' => env('LABEL_PRINTER_QUEUE'),
    'print_command' => env('LABEL_PRINT_COMMAND', 'lp'),
    'templates' => [
        'dymo-99010-89x36' => [
            'name' => 'Dymo 99010 (89 x 36 mm) – Standard Address',
            'width_mm' => 89,
            'height_mm' => 36,
            'qr_size' => 240,
            'padding_mm' => 1.5,
            'qr_column_mm' => 48,
            'caption_font_size' => 8,
            'caption_lines' => 6,
            'caption_wrap' => 30,
        ],
        'dymo-30334-57x32' => [
            'name' => 'Dymo 30334 (57 x 32 mm) – Multi-Purpose',
            'width_mm' => 57,
            'height_mm' => 32,
            'qr_size' => 220,
            'padding_mm' => 1.2,
            'qr_column_mm' => 30,
            'caption_font_size' => 8,
            'caption_lines' => 5,
            'caption_wrap' => 28,
        ],
        'dymo-30336-54x25' => [
            'name' => 'Dymo 30336 (54 x 25 mm) – Return Address',
            'width_mm' => 54,
            'height_mm' => 25,
            'qr_size' => 210,
            'padding_mm' => 1.1,
            'qr_column_mm' => 28,
            'caption_font_size' => 7.5,
            'caption_lines' => 5,
            'caption_wrap' => 26,
        ],
        'dymo-99012-36x89' => [
            'name' => 'Dymo 99012 (89 x 36 mm) – Standard Address',
            'width_mm' => 89,
            'height_mm' => 36,
            'qr_size' => 240,
            'padding_mm' => 1.5,
            'qr_column_mm' => 48,
            'caption_font_size' => 8.5,
            'caption_lines' => 5,
            'caption_wrap' => 32,
        ],
        'dymo-30256-59x101' => [
            'name' => 'Dymo 30256 (101 x 59 mm) – Shipping',
            'width_mm' => 101,
            'height_mm' => 59,
            'qr_size' => 280,
            'padding_mm' => 2,
            'qr_column_mm' => 58,
            'caption_font_size' => 9,
            'caption_lines' => 5,
            'caption_wrap' => 36,
        ],
        'dymo-89x36' => [
            'name' => 'Legacy Custom (50 x 30 mm)',
            'width_mm' => 50,
            'height_mm' => 30,
            'qr_size' => 200,
            'padding_mm' => 1.2,
            'qr_column_mm' => 26,
            'caption_font_size' => 8,
            'caption_lines' => 5,
            'caption_wrap' => 28,
        ],
    ],
];
